import Head from 'next/head'
import styles from '../styles/Home.module.css'
/*

    Yes 

*/


function About() {
    return (
    
    <div className={styles.container}>
      <Head>
        <title>About | Wellcome to the SinanZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          About
        </h1>

        <p className={styles.description}>
        lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten 
        ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor <br></br>
        sit amet ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten lorem 
        ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten 
        ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet <br></br> <br></br>
         ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet 
         ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet  <br></br>
         ten ten lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten ten 
        </p>
        </main>
    </div>
    
    )
  }
  
  export default About