import Head from 'next/head'
import styles from '../styles/Home.module.css'
/*

    Yes 

*/


function About() {
    return (
    
    <div className={styles.container}>
      <Head>
        <title>About | Wellcome to the SinanZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          About
        </h1>

        <nav className={styles.navmenu}>
        <link href="/">SinanZone!</link> 
        <link href="/about">About</link> 
        <link href="/contact">Contact</link> 
        </nav>



        <p className={styles.description}>
        lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten  ipsum dolor <br></br>
        lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit et ten  ipsum dolor <br></br>
        lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten  ipsum dolor <br></br>
        lorem ipsum dolor   ipsum dolor <br></br>
        lorem ipsum dolor sit amet ten ten lorem ipsum dolor sit amet ten  ipsum dolor <br></br>
        lorem ipsum dolor sit amet ten teorem ipsum dolor sit amet ten  ipsum dolor <br></br>
        lorem ipsum dolor sit amet tenen lorem ipsum dolor sit amet ten  ipsum dolor <br></br>
        lorem ipsum dolor sit amen ten lorem ipsum dolor sit amet ten  ipsum dolor <br></br>
        </p>
        </main>
    </div>
    
    )
  }
  
  export default About