import Head from 'next/head'
import styles from '../styles/Home.module.css'
/*

    Yes 

*/


function About() {
    return (
    
    <div className={styles.container}>
      <Head>
        <title>About | Wellcome to the SinanZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Contact
        </h1>

        <nav className={styles.navmenu}>
        <a href="/">SinanZone!</a> 
        <a href="/about">About</a> 
        <a href="/contact">Contact</a> 
        </nav>



        <p className={styles.description}>
        
            
            <a href="https://github.com/sinanisler">https://github.com/sinanisler</a>  <br></br>  <br></br> 

            <a href="mailto:sinan@sinanisler.com">sinan@sinanisler.com</a>   <br></br>  <br></br> 

            <a href="https://linkedin.com/in/sinanisler">https://linkedin.com/in/sinanisler</a>  <br></br>  <br></br>
        
        </p>
        </main>
    </div>
    
    )
  }
  
  export default About